config/routes.rb
Rails.application.routes.draw do
  resources :universities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/university.rb
class University < ApplicationRecord
	validates :name, uniqueness: true, presence: true
	validates :faculty_members, presence: true, numericality: {only_integer: true}, numericality: {greater_than: 0}
	validates :city, presence: true
	validates :total_students, presence: true, numericality: {only_integer: true}, numericality: {greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: %i[ show edit update destroy ]

  # GET /universities or /universities.json
  def index
    @num = 1
    @universities = University.all
  end

  # GET /universities/1 or /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities or /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to university_url(@university), notice: "University was successfully created." }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1 or /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to university_url(@university), notice: "University was successfully updated." }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1 or /universities/1.json
  def destroy
    @university.destroy

    respond_to do |format|
      format.html { redirect_to universities_url, notice: "University was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def university_params
      params.require(:university).permit(:name, :faculty_members, :city, :total_students)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/universities/_form.html.erb
<div class="container">
  <%= form_with(model: university, local: true) do |form| %>
    <% if university.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(university.errors.count, "error") %> prohibited this university from being saved:</h2>

        <ul>
          <% university.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="card shadow">
      <div class="card body">
        <div class="form.group mb-2">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control form-control", id: "nameChk", onchange:"myFunction" %>
          <p id="demo"></p>
          <script>
            document.getElementById("nameChk").addEventListener('change', function() {
              debugger
            })
            function myFunction() {
              debugger;
              var x = document.getElementById("nameChk").value;
              console.log(x);
              var letters = /^[A-Za-z]+$/;
              console.log(x.value.match(letters));
            }
          </script>
        </div>
        <div class="fomr.group mb-2">
          <%= form.label :city %>
          <%= form.text_field :city, class: "form-control form-lg" %>
        </div>
        <div class="fomr.group mb-2">
          <%= form.label :faculty_members %>
          <%= form.number_field :faculty_members, class: "form-control form-lg" %>
        </div>
        <div class="fomr.group mb-2">
          <%= form.label :total_students %>
          <%= form.number_field :total_students, class: "form-control form-lg" %>
        </div>
         <div class="actions">
          <button type="submit", class="btn btn-primary">Submit</button>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <h1 >Universities</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>no#</th>
        <th>Univerity name </th>
        <th>City name </th>
        <th>Faculty members </th>
        <th>Total students </th>

      </tr>
    </thead>
    <tbody>
      <% @universities.each do |university| %>
      <tr>
        
        <td> <%= @num %></td>
        <td><%= university.name %></td>
        <td><%= university.city %></td>
        <td><%= university.faculty_members %></td>
        <td><%= university.total_students %></td>
        <td><%= link_to 'Show', university, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_university_path(university), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
        <%@num = @num+1%>
     <% end %>

    </tbody>
  </table>
  <%= link_to 'New University', new_university_path, class: "btn btn-primary" %>
</div>



<div class="container">
  <p id="play">ok</p>
  <script >
    document.getElementById("play").innerHTML = "Lets play with JavaScript"
  </script>

  <p id="try">Using button</p>
  <script >
    function myFunction(){
      document.getElementById("try").innerHTML = "Inside the function"
    }
  </script>
  <button type="button" onclick = "myFunction()" class="btn btn-info">Press</button>
  <br>

 <!--  <script >
    document.write(6+6)
  </script> -->
  <br>
  <!-- <script >
    window.alert(10+5)
  </script>
  <script >
    alert(5+1)
  </script> -->

  <script >
    console.log(12+6)
  </script>
  <p id="cr"></p>
  <p id="rcr"></p>
  <p id="scr"></p>
  <script >
    var cars = ["Audi","Toyota","Prius","Suzuki"]
    document.getElementById("cr").innerHTML = cars;
  </script>
  <script >
    cars.reverse();
    document.getElementById("rcr").innerHTML = cars;
  </script>
  <script >
    cars.sort();
    document.getElementById("scr").innerHTML = cars;
  </script>
  <p id="n2"></p>

  <script >
    const numbers1 = [45, 4, 9, 16, 25];
    const numbers2 = numbers1.map(myFunction);

    document.getElementById("n2").innerHTML = numbers2;

    function myFunction(value) {
    return value * 3;
}
  </script>
  <p id="fl"></p>
  <script>
    var number1 = [15,14,13,12,11,16,17,18,19];
    var number2 = number1.filter(myFunc);
    document.getElementById("fl").innerHTML = number2;

    function myFunc(value, index,array){
      value =value * 2;
      return value>30
    }
  </script>
  <p id="d"></p>
  <script >
    var date = new Date()
    document.getElementById("d").innerHTML = date;
  </script>
   <p id="da"></p>
  <script >
    var date = new Date()
    document.getElementById("da").innerHTML = date.getFullYear();
  </script>

  <p id="set"></p>
  <script >
    var setV = new Set(["a","b","c"]);
    document.getElementById("set").innerHTML = setV.size;

    setV.add("d");
    document.getElementById("set").innerHTML = setV;
  </script>

  <p id="debug"></p>
  <script >
    var x = 18*2;
    document.getElementById(debug).innerHTML = x;

  </script>
  <div onmouseover="mOver(this)" onmouseout="mOut(this)" style="background-color:#D94A38;width:120px;height:20px;padding:40px;">Mouse!</div>
  <script >
    function mOver(obj){
      obj.innerHTML = "Thanks"
    }
    function mOut(obj){
      obj.innerHTML = "Bye"
    }
  </script>




</div>

app/views/universities/new.html.erb
<div class="container">
<div class="card shadow">
<h1 class="text text-primary">New University</h1>
<div class="card-header"><%= render 'form', university: @university %></div>

<div class="card-body"><%= link_to 'Back', universities_path %></div>
</div>
</div>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @university.name %>
</p>

<p>
  <strong>Faculty members:</strong>
  <%= @university.faculty_members %>
</p>

<p>
  <strong>City:</strong>
  <%= @university.city %>
</p>

<p>
  <strong>Total students:</strong>
  <%= @university.total_students %>
</p>

<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>